# version: '3.8'

# services:

#   apm-server:
#     image: docker.elastic.co/apm/apm-server:7.13.0
#     cap_add: ["CHOWN", "DAC_OVERRIDE", "SETGID", "SETUID"]
#     cap_drop: ["ALL"]
#     ports:
#     - 8200:8200
#     command: >
#        apm-server -e
#          -E apm-server.rum.enabled=true
#          -E setup.kibana.host=kibana:5601
#          -E setup.template.settings.index.number_of_replicas=0
#          -E apm-server.kibana.enabled=true
#          -E apm-server.kibana.host=kibana:5601
#          -E output.elasticsearch.hosts=["elasticsearch:9200"]
#     healthcheck:
#       interval: 10s
#       retries: 12
#       test: curl --write-out 'HTTP %{http_code}' --fail --silent --output /dev/null http://localhost:8200/
  
#   elasticsearch:
#    container_name: elasticsearch
#    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.0
#    ports:
#     - 9200:9200
#    volumes:
#     - elasticsearch-data:/usr/share/elasticsearch/data
#    environment:
#     - xpack.monitoring.enabled=true
#     - xpack.watcher.enabled=false
#     - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#     - discovery.type=single-node
#    networks:
#     - elastic

#   kibana:
#    container_name: kibana
#    image: docker.elastic.co/kibana/kibana:7.13.0
#    ports:
#     - 5601:5601
#    depends_on:
#     - elasticsearch
#    environment:
#     - ELASTICSEARCH_URL=http://localhost:9200
#     - xpack.apm.enabled=false
#    networks:
#     - elastic

#   jaeger: 
#     image: jaegertracing/all-in-one
#     environment: 
#       - COLLECTOR_ZIPKIN_HTTP_PORT=9411
#     depends_on:
#       - elasticsearch
#     ports:
#       - "5775:5775/udp"
#       - "6831:6831/udp"
#       - "6832:6832/udp"
#       - "5778:5778"
#       - "16686:16686" ##UI
#       - "14268:14268"
#       - "14250:14250"
#       - "9411:9411"
  
# networks:
#   elastic:
#     driver: bridge

# volumes:
#   elasticsearch-data:

version: "3.0"
services:

  apm-server:
    container_name: apmserver
    image: docker.elastic.co/apm/apm-server:7.17.24
    cap_add: ["CHOWN", "DAC_OVERRIDE", "SETGID", "SETUID"]
    cap_drop: ["ALL"]
    ports:
      - 8200:8200
    command: >
      apm-server -e
        -E apm-server.rum.enabled=true
        -E setup.kibana.host=kibana:5601
        -E setup.template.settings.index.number_of_replicas=0
        -E apm-server.kibana.enabled=true
        -E apm-server.kibana.host=kibana:5601
        -E output.elasticsearch.hosts=["elasticsearch:9200"]
    healthcheck:
      interval: 10s
      retries: 12
      test: curl --write-out 'HTTP %{http_code}' --fail --silent --output /dev/null http://localhost:8200/
    networks:
      - elastic 

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.24
    ports:
      - 9200:9200
    environment:
      - xpack.monitoring.enabled=true
      - xpack.watcher.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    networks:
      - elastic

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.17.24
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_URL=http://localhost:9200
      - xpack.apm.enabled=false
    networks:
      - elastic

networks:
  elastic:
    driver: bridge